// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Mar 2016 22:25:38 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "libpostal.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

