// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Feb 2016 05:10:19 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "libpostal.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

