// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 Sep 2016 16:22:35 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "libpostal.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

