// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Feb 2016 05:10:19 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package postal provides Go bindings for libpostal, a C library for fast international street address parsing and normalization.
*/
package postal
