// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Mar 2016 22:25:38 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package postal provides Go bindings for libpostal, a C library for fast international street address parsing and normalization.
*/
package postal
