// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 Sep 2016 16:22:35 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package postal provides Go bindings for libpostal, a C library for fast international street address parsing and normalization.
*/
package postal
