// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Feb 2016 05:10:19 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package postal

/*
#cgo pkg-config: libpostal
#include "libpostal.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// GetLibpostalDefaultOptions function as declared in postal/libpostal.h:65
func GetLibpostalDefaultOptions() NormalizeOptions {
	__ret := C.get_libpostal_default_options()
	__v := *NewNormalizeOptionsRef(&__ret)
	return __v
}

// ExpandAddress function as declared in postal/libpostal.h:67
func ExpandAddress(input []byte, options NormalizeOptions, n []uint) **byte {
	cinput, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&input)).Data)), cgoAllocsUnknown
	coptions, _ := options.PassValue()
	cn, _ := (*C.size_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&n)).Data)), cgoAllocsUnknown
	__ret := C.expand_address(cinput, coptions, cn)
	__v := *(***byte)(unsafe.Pointer(&__ret))
	return __v
}

// ExpansionArrayDestroy function as declared in postal/libpostal.h:69
func ExpansionArrayDestroy(expansions [][]byte, n uint) {
	cexpansions, _ := unpackArgSSByte(expansions)
	cn, _ := (C.size_t)(n), cgoAllocsUnknown
	C.expansion_array_destroy(cexpansions, cn)
	packSSByte(expansions, cexpansions)
}

// AddressParserResponseDestroy function as declared in postal/libpostal.h:86
func AddressParserResponseDestroy(self *AddressParserResponse) {
	cself, _ := self.PassRef()
	C.address_parser_response_destroy(cself)
}

// GetLibpostalAddressParserDefaultOptions function as declared in postal/libpostal.h:88
func GetLibpostalAddressParserDefaultOptions() AddressParserOptions {
	__ret := C.get_libpostal_address_parser_default_options()
	__v := *NewAddressParserOptionsRef(&__ret)
	return __v
}

// ParseAddress function as declared in postal/libpostal.h:90
func ParseAddress(address []byte, options AddressParserOptions) *AddressParserResponse {
	caddress, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&address)).Data)), cgoAllocsUnknown
	coptions, _ := options.PassValue()
	__ret := C.parse_address(caddress, coptions)
	__v := NewAddressParserResponseRef(__ret)
	return __v
}

// Setup function as declared in postal/libpostal.h:94
func Setup() bool {
	__ret := C.libpostal_setup()
	__v := (bool)(__ret)
	return __v
}

// Teardown function as declared in postal/libpostal.h:95
func Teardown() {
	C.libpostal_teardown()
}

// SetupParser function as declared in postal/libpostal.h:97
func SetupParser() bool {
	__ret := C.libpostal_setup_parser()
	__v := (bool)(__ret)
	return __v
}

// TeardownParser function as declared in postal/libpostal.h:98
func TeardownParser() {
	C.libpostal_teardown_parser()
}

// SetupLanguageClassifier function as declared in postal/libpostal.h:100
func SetupLanguageClassifier() bool {
	__ret := C.libpostal_setup_language_classifier()
	__v := (bool)(__ret)
	return __v
}

// TeardownLanguageClassifier function as declared in postal/libpostal.h:101
func TeardownLanguageClassifier() {
	C.libpostal_teardown_language_classifier()
}
